service:
  name: dev-auth-server

custom:
  functionsBasePath: src/handlers
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  customDomain:
    domainName: auth.linkube.com
    stage: v1
    basePath: ""
    certificateName: "*.linkube.com"
    createRoute53Record: true
    endpointType: "regional"
    securityPolicy: tls_1_2
    apiType: rest

  # fix: sls offline reload not working
  serverless-offline:
    useChildProcesses: true

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-domain-manager

provider:
  name: aws
  runtime: nodejs12.x
  region: region, 'ap-northeast-2'
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
    binaryMediaTypes:
      - "*/*"
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

functions:
  hello:
    handler: src/server.handler
    events:
      - http: ANY /
      - http: "ANY {proxy+}"
